CREATE TABLE superpoder
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome              VARCHAR(255),
    descricao         VARCHAR(255),
    nivel_inutilidade INTEGER NOT NULL,
    CONSTRAINT pk_superpoder PRIMARY KEY (id)
);